---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
__driver_options: &opts
  pre_build_image: true
  command: /sbin/init
  tmpfs:
    - /run
    - /tmp
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
platforms:
  - name: el-7
    image: docker.io/library/centos:7
    <<: *opts
  - name: el-8
    image: docker.io/library/centos:8
    <<: *opts
provisioner:
  name: ansible
verifier:
  name: ansible
